### PR TITLE
fix: use new image metadata as destination when copying exif data

### PR DESCRIPTION
**Pull request by murat-mehmet**
## Summary

Currently on iOS exif metadata is copied from the new file to the old file, this causes new orientation value to be ignored. The orientation from the old file causes image to be displayed incorrectly.

Solution is to actually copy from source to the new metadata and use the new one.

## Changelog

fixed copy exif on iOS

## Test Plan

Test compression of an image with rotated orientation.

### CODE REVIEW

**Review by numandev1 — APPROVED** [review]
LGTM

**Comment by numandev1** [comment]
@murat-mehmet can you checkout this use case in android?

**Comment by numandev1** [comment]
@murat-mehmet released in 1.8.22

**Comment by murat-mehmet** [comment]
> @murat-mehmet can you checkout this use case in android?

android works well in this case 👍

**Pull request merged**
