### PR TITLE
fix: cannot find 'kAudioFormatAPAC' in scope

### PR DESCRIPTION
**Pull request by numandev1**
## Summary
fix https://github.com/numandev1/react-native-compressor/issues/322 https://github.com/numandev1/react-native-compressor/issues/323

## Changelog

[CATEGORY] [TYPE] - Message

### CODE REVIEW

**Comment by phuocnguyenncc** [comment]
@numandev1 i tried but not working

**Comment by numandev1** [comment]
@phuocnguyenncc can we have a live session for debugging it as it is not reproducible on my side

**Comment by numandev1** [comment]
https://www.linkedin.com/in/numandev/ here you can connect with me https://www.linkedin.com/in/numandev/

**Comment by phuocnguyenncc** [comment]
@numandev1 oki. thank you

**Comment by numandev1** [comment]
@phuocnguyenncc can you try https://github.com/numandev1/react-native-compressor/releases/tag/v1.10.3

**Pull request merged**
